# Generated by Django 4.2.25 on 2025-10-27 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogos', '0002_socioshistoriaaccion'),
        ('socios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocioHistoria',
            fields=[
                ('sociohistoriaid', models.AutoField(primary_key=True, serialize=False)),
                ('numero_socio', models.CharField(blank=True, max_length=50)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_accion', models.DateTimeField(auto_now_add=True)),
                ('accion', models.ForeignKey(db_column='accionid', on_delete=django.db.models.deletion.PROTECT, to='catalogos.socioshistoriaaccion')),
                ('categoria', models.ForeignKey(blank=True, db_column='categoriasocioid', null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogos.categoriasocio')),
                ('estado', models.ForeignKey(blank=True, db_column='socioestadoid', null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogos.sociosestado')),
                ('socio', models.ForeignKey(db_column='socioid', on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='socios.socio')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_socios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historia de Socio',
                'verbose_name_plural': 'Historias de Socios',
                'db_table': 'socios_historia',
                'ordering': ['-fecha_accion'],
                'managed': True,
            },
        ),
    ]
