# Generated by Django 4.2.25 on 2025-10-27 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaSocio',
            fields=[
                ('categoriasocioid', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=200)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'categorias_socio',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('filialid', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=200)),
                ('domicilio', models.CharField(blank=True, max_length=300)),
                ('vigente', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'filiales',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SociosEstado',
            fields=[
                ('socioestadoid', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('vigente', models.BooleanField(default=True)),
                ('indica_socio_activo', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'socios_estado',
                'managed': True,
            },
        ),
    ]
