# Generated by Django 4.2.25 on 2025-10-27 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SociosHistoriaAccion',
            fields=[
                ('accionid', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Acción',
                'verbose_name_plural': 'Acciones',
                'db_table': 'socios_historia_accion',
                'managed': True,
            },
        ),
    ]
