# Generated by Django 4.2.25 on 2025-10-27 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('persona', models.OneToOneField(db_column='personaid', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='personas.persona')),
                ('numero_socio', models.CharField(blank=True, max_length=50)),
                ('fecha_alta', models.DateField()),
                ('categoria', models.ForeignKey(db_column='categoriasocioid', on_delete=django.db.models.deletion.PROTECT, to='catalogos.categoriasocio')),
                ('estado', models.ForeignKey(db_column='socioestadoid', on_delete=django.db.models.deletion.PROTECT, to='catalogos.sociosestado')),
                ('filial', models.ForeignKey(blank=True, db_column='filialid', null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogos.filial')),
            ],
            options={
                'db_table': 'socios',
                'managed': True,
            },
        ),
    ]
