# Generated by Django 4.2.25 on 2025-10-27 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocioGrupoFamiliar',
            fields=[
                ('grupofamiliarid', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_desde', models.DateField()),
                ('fecha_hasta', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Grupo Familiar',
                'verbose_name_plural': 'Grupos Familiares',
                'db_table': 'socios_grupo_familiar',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SocioGrupoFamiliarMiembro',
            fields=[
                ('grupofamiliarmiembroid', models.BigAutoField(primary_key=True, serialize=False)),
                ('es_titular', models.BooleanField(default=False)),
                ('fecha_alta', models.DateField()),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('grupo_familiar', models.ForeignKey(db_column='grupofamiliarid', on_delete=django.db.models.deletion.CASCADE, related_name='miembros', to='socios.sociogrupofamiliar')),
                ('socio', models.ForeignKey(db_column='personaid', on_delete=django.db.models.deletion.CASCADE, related_name='grupos_familiares', to='socios.socio')),
            ],
            options={
                'verbose_name': 'Miembro de Grupo Familiar',
                'verbose_name_plural': 'Miembros de Grupos Familiares',
                'db_table': 'socios_grupo_familiar_miembros',
                'managed': True,
                'unique_together': {('grupo_familiar', 'socio')},
            },
        ),
    ]
