# Generated by Django 4.2.25 on 2025-10-27 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0002_sociogrupofamiliar_sociogrupofamiliarmiembro'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocioDiscapacidad',
            fields=[
                ('socio', models.OneToOneField(db_column='personaid', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='discapacidad', serialize=False, to='socios.socio')),
                ('numero_certificado', models.CharField(blank=True, max_length=100)),
                ('tipo_discapacidad', models.CharField(blank=True, max_length=200)),
                ('fecha_desde', models.DateField()),
                ('fecha_hasta', models.DateField(blank=True, null=True)),
                ('auditor_responsable', models.CharField(blank=True, max_length=200)),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Certificado de Discapacidad',
                'verbose_name_plural': 'Certificados de Discapacidad',
                'db_table': 'socios_discapacidad',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SocioDomicilioPagoSas',
            fields=[
                ('socio', models.OneToOneField(db_column='personaid', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='domicilio_pago_sas', serialize=False, to='socios.socio')),
                ('calle', models.CharField(blank=True, max_length=200)),
                ('numero', models.CharField(blank=True, max_length=10)),
                ('piso', models.CharField(blank=True, max_length=10)),
                ('departamento', models.CharField(blank=True, max_length=10)),
                ('codigo_postal', models.CharField(blank=True, max_length=10)),
                ('localidad', models.CharField(blank=True, max_length=100)),
                ('provincia', models.CharField(blank=True, max_length=100)),
                ('pais', models.CharField(blank=True, default='Argentina', max_length=100)),
            ],
            options={
                'verbose_name': 'Domicilio de Pago SAS',
                'verbose_name_plural': 'Domicilios de Pago SAS',
                'db_table': 'socios_domicilio_pago_sas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SocioDiscapacidadAcompanante',
            fields=[
                ('acompananteid', models.BigAutoField(primary_key=True, serialize=False)),
                ('apellido', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('documento', models.CharField(max_length=20)),
                ('tipo_documento', models.CharField(blank=True, default='DNI', max_length=20)),
                ('vinculo', models.CharField(blank=True, max_length=100)),
                ('fecha_desde', models.DateField()),
                ('fecha_hasta', models.DateField(blank=True, null=True)),
                ('socio_discapacidad', models.ForeignKey(db_column='personaid', on_delete=django.db.models.deletion.CASCADE, related_name='acompanantes', to='socios.sociodiscapacidad')),
            ],
            options={
                'verbose_name': 'Acompañante',
                'verbose_name_plural': 'Acompañantes',
                'db_table': 'socios_discapacidad_acompanantes',
                'managed': True,
            },
        ),
    ]
