# Generated by Django 4.2.25 on 2025-10-27 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persona',
            options={'managed': True, 'verbose_name': 'Persona', 'verbose_name_plural': 'Personas'},
        ),
        migrations.CreateModel(
            name='TelefonoPersona',
            fields=[
                ('telefonopersonaid', models.BigAutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=50)),
                ('tipo', models.CharField(blank=True, default='Celular', max_length=20)),
                ('caracteristica', models.CharField(blank=True, max_length=10)),
                ('principal', models.BooleanField(default=False)),
                ('persona', models.ForeignKey(db_column='personaid', on_delete=django.db.models.deletion.CASCADE, related_name='telefonos', to='personas.persona')),
            ],
            options={
                'verbose_name': 'Teléfono',
                'verbose_name_plural': 'Teléfonos',
                'db_table': 'telefonos_persona',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EmailPersona',
            fields=[
                ('emailpersonaid', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=200)),
                ('principal', models.BooleanField(default=False)),
                ('validado', models.BooleanField(default=False)),
                ('persona', models.ForeignKey(db_column='personaid', on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='personas.persona')),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Emails',
                'db_table': 'emails_persona',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DomicilioPersona',
            fields=[
                ('domiciliopersonaid', models.BigAutoField(primary_key=True, serialize=False)),
                ('calle', models.CharField(blank=True, max_length=200)),
                ('numero', models.CharField(blank=True, max_length=10)),
                ('piso', models.CharField(blank=True, max_length=10)),
                ('departamento', models.CharField(blank=True, max_length=10)),
                ('codigo_postal', models.CharField(blank=True, max_length=10)),
                ('localidad', models.CharField(blank=True, max_length=100)),
                ('provincia', models.CharField(blank=True, max_length=100)),
                ('principal', models.BooleanField(default=False)),
                ('persona', models.ForeignKey(db_column='personaid', on_delete=django.db.models.deletion.CASCADE, related_name='domicilios', to='personas.persona')),
            ],
            options={
                'verbose_name': 'Domicilio',
                'verbose_name_plural': 'Domicilios',
                'db_table': 'domicilios_persona',
                'managed': True,
            },
        ),
    ]
