# Generated by Django 4.2.25 on 2025-10-27 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_alter_persona_options_telefonopersona_emailpersona_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persona',
            options={'managed': True, 'ordering': ['apellido', 'nombre'], 'verbose_name': 'Persona', 'verbose_name_plural': 'Personas'},
        ),
    ]
