# Generated by Django 4.2.25 on 2025-10-29 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_alter_persona_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domiciliopersona',
            options={'managed': False, 'verbose_name': 'Domicilio', 'verbose_name_plural': 'Domicilios'},
        ),
        migrations.AlterModelOptions(
            name='emailpersona',
            options={'managed': False, 'verbose_name': 'Email', 'verbose_name_plural': 'Emails'},
        ),
        migrations.AlterModelOptions(
            name='persona',
            options={'managed': False, 'ordering': ['apellido', 'nombre'], 'verbose_name': 'Persona', 'verbose_name_plural': 'Personas'},
        ),
        migrations.AlterModelOptions(
            name='telefonopersona',
            options={'managed': False, 'verbose_name': 'Teléfono', 'verbose_name_plural': 'Teléfonos'},
        ),
    ]
